apiVersion : apps/v1
kind : Deployment
metadata : 
  name : client-deployment
spec :
  replicas : 1
  selector : 
    matchLabels : 
      component : webapp
  template :
    metadata :
      labels :
        component : webapp
    spec :
      containers :
        - name  : webapp
          image : vinothrao247/recruitmanagewebwpp
          ports :
            - containerPort : 4000


