version : "3.0"
services:
  recruitmanageapi:
    build:
      context: .
      dockerfile : RecruitManageAPI/Dockerfile
    ports:
      - "8080:8080"
  webapp:
    build:
      context : .
      dockerfile : RecruitManage/Dockerfile
    ports:
      - "4000:4000"
      
  #added nginx proxy to route the requests between api and fron end since frond end js cannot call 
  #api inside docker though docker compose networking
  nginx:
    restart : always
    build:
      context : .
      dockerfile : RecruitManage/nginx/Dockerfile
    ports:
      - "3050:80"